version: "3.7"

services:
  accountservice:
    image: meisha:latest
    restart: always
    #volumes:
    # - ./appsettings.json:/home/docker/meisha/appsettings.yaml
    ports:
     - "3500:3500"
    environment:
      - DAPR_HTTP_PORT=3500
      - DOCKER_BASEPATH=host.docker.internal
  accountservice-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
     "-app-id", "accountservice",
     "-app-port", "8050",
     "-dapr-http-port", "3500",
     "-components-path", "/components/",
     "-placement-host-address", "host.docker.internal:6050" # Dapr's placement service can be reach via the docker DNS entry
     ]
    #ports:
    # - "3503:3500"
    # - "9090:9090"
    volumes:
        - "./components/:/components"
    depends_on:
      - accountservice
    network_mode: "service:accountservice" # service:accountservice